language: cpp
sudo: required
dist: trusty
compiler:
- gcc 
os:
- linux
before_install:
- echo $LANG
- echo $LC_ALL
- ./scripts/dependencies.sh
before_script: 
- sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
- gcc --version
- cmake .
script:
- make -j 4
branches:
  only:
  - master
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
