language: cpp
sudo: required
dist: trusty
compiler:
- g++
os:
- linux
before_install:
- ./scripts/dependencies.sh
before_script: 
- sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
- gcc --version
- g++ --version
- cmake .
script:
- make -j 4
branches:
  only:
  - master
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - clang-3.8 
    - llvm-3.8-dev 
    - cmake 
    - doxygen
