language: cpp
sudo: required
dist: trusty
compiler:
- g++-5
os:
- linux
before_install:
- ./scripts/dependencies.sh
before_script: 
- g++ --version
- cmake .
script:
- make -j 4
branches:
  only:
  - master
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - clang-3.8 
    - llvm-3.8-dev 
    - cmake 
    - doxygen
